feat:  file added to fetch data from the subgraph API. Package.json updated with axios and ts-node.
w3b3d3v/web3task-front pull request #154
Opened 2023-11-24 17:39 UTC by RafaDSan

closes #153 

@Guboehm Made the `subgraph-queries.ts` file using axios to fetch data from the subgraph API.

2023-12-07 01:24 UTC, 0xneves requested changes
I'm requesting a change to add the auth keys and URL path into the environment file. Fetch them when running the script.

2023-12-07 01:24 UTC, 0xneves commented on src/services/subgraph-queries.ts
Sensitive data should not be committed into the codebase

2023-12-07 14:19 UTC, RafaDSan commented
@0xneves Changes made as suggested!

- Added the `.env-sample` file to be fetched by the  `subgraph-queries.ts` file
- endpoint URL and authorization key are now hidden by the `.env`
- package.json updated to accept the dotenv dependencies.


The commit 6d05195b477a11955654b86594853cd844373e70 which adds an `.env` file to the frontend closes #157

2023-12-08 02:18 UTC, 0xneves approved these changes

2023-12-08 02:18 UTC, merged